spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.10.134:3306/oauth2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
# --- server
server:
  port: 8082



